### ISSUE TITLE
Cannot install gem via GitHub

### ISSUE THREAD

**Issue by slabstone** [deb-s3/deb-s3#12]
Running command from https://github.com/deb-s3/deb-s3/packages/304683 yields:

```
# gem install deb-s3 --version "0.11.3" --source "https://rubygems.pkg.github.com/deb-s3"
ERROR:  Could not find a valid gem 'deb-s3' (= 0.11.3), here is why:
          Unable to download data from https://rubygems.pkg.github.com/deb-s3/ - bad response Unauthorized 401 (https://rubygems.pkg.github.com/deb-s3/specs.4.8.gz)
ERROR:  Possible alternatives: deb-s3
```

**Comment by GMartinez-Sisti** [comment]
I was also surprised to discover you need a token to install from Github Packages -> https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-rubygems-registry#installing-a-package.

Alternatives are using bundler, add this to `Gemfile`:
```
gem 'deb-s3', '0.11.3', git: 'https://github.com/deb-s3/deb-s3'
```

Or downloading and installing directly as explained here -> https://github.com/deb-s3/deb-s3#getting-started

**Comment by morph027** [comment]
We also finally managed to distribute ownership and latest version has been uploaded to rubygems already. Will update README later.
