### ISSUE TITLE
Add S3 permissions requirements and debugging

### ISSUE THREAD

**Issue by mjlabe** [deb-s3/deb-s3#20]
I am debugging the error `Aws::S3::Errors::AccessDenied` but there is no info on the required persons for the key. The debug info is also not helpful to see what permission is missing.

**Comment by mjlabe** [comment]
Looks like the error is coming from the aws sdk, so not much to do there. But I still don't know what permissions I need.

**Comment by morph027** [comment]
https://github.com/krobertson/deb-s3/issues/118#issuecomment-286723982

**Comment by mjlabe** [comment]
Thanks! I searched issues here, but not the original repo. PR submitted for the ReadMe.
