### ISSUE TITLE
Can I use latest deb-s3 version to create ppa for Ubuntu 20.04 (focal)

### ISSUE THREAD

**Issue by arbabnazar** [deb-s3/deb-s3#3]
Can I use latest deb-s3 version to create ppa for Ubuntu 20.04 (focal)

**Comment by morph027** [comment]
I'm creating repos for focal with this version, so yes ;)

**Comment by arbabnazar** [comment]
@morph027 thank you, when we'll expect that version please?

**Comment by scalp42** [comment]
@arbabnazar he's saying you can create PPAs already 😅

**Comment by morph027** [comment]
Jip. I guess you refer to the PR https://github.com/krobertson/deb-s3/pull/164 which has been merged into this with https://github.com/deb-s3/deb-s3/commit/b305fefbaa089ef66d5d2b7a2bb7e9965c8bf82f.

I still can't release on rubygems, as the original package belongs to @krobertson, so you need to install manually like written in the [README](https://github.com/deb-s3/deb-s3#getting-started)
