### ISSUE TITLE
deb-s3 github action

### ISSUE THREAD

**Issue by Alw3ys** [deb-s3/deb-s3#41]
Hey there, I've created this github action to set it up easily.

Wanted to mention it here: https://github.com/Alw3ys/setup-deb-s3

Maybe someone can find it useful it would be interesting to add it to the README if someone wants it out of the box?

Happy to make a PR with whatever you want to do with it :D.

Happy to also transfer repo to this org so you can take ownership of it and I can maintain it.

**Comment by Alw3ys** [comment]
Hey @morph02

I've changed the LICENSE to MIT and granted you as a copyright holder, if I get access to create public repos on the org I'll can transfer the repo and make the org owner. I'll maintain it.

![Screenshot 2024-04-22 at 17 38 07](https://github.com/deb-s3/deb-s3/assets/8609017/9721041c-b818-450a-90d1-9edc34380305)

**Comment by morph027** [comment]
Oh, sorry for the delay, just forgot about. Thanks for your effort 👍  Will add you to the organization. Welcome!

**Comment by Alw3ys** [comment]
No problem! Awesome! Transfered, will make the changes so README on the new repo reflects new organization! Thanks!

**Comment by Alw3ys** [comment]
Done! Ready to be used, let me know if you would like me to change anything!
