### ISSUE TITLE
Bug in Ubuntu 24.04 Noble's ruby-aws-partitions package causes deb-s3 error

### ISSUE THREAD

**Issue by ShaunMaher** [deb-s3/deb-s3#47]
**This is not a bug in deb-s3.**  I'm submitting this issue just so the next poor sucker doesn't need to work it out from scratch.

```
/usr/share/rubygems-integration/all/gems/aws-partitions-1.653.0/lib/aws-partitions.rb:235:in `read': No such file or directory @ rb_sysopen - /usr/share/rubygems-integration/all/gems/aws-partitions-1.653.0/partitions-metadata.json (Errno::ENOENT)
	from /usr/share/rubygems-integration/all/gems/aws-partitions-1.653.0/lib/aws-partitions.rb:235:in `default_metadata'
...
```

The Ubuntu ruby-aws-partitions package version `1.653.0-2` is missing the file `/usr/share/rubygems-integration/all/gems/aws-partitions-1.653.0/partitions-metadata.json`.  The upstream Debian package `1.653.0-3` does include the file.  Hopefully this means that Ubuntu will pull the fixed package eventually.

In the mean time, you can download the Debian package and extract the missing file:
```bash
wget -o /tmp/uby-aws-partitions/ruby-aws-partitions_1.653.0-3_all.deb "http://http.us.debian.org/debian/pool/main/r/ruby-aws-partitions/ruby-aws-partitions_1.653.0-3_all.deb"
mkdir /tmp/ruby-aws-partitions
dpkg-deb -x /var/cache/ruby-aws-partitions_1.653.0-3_all.deb /tmp/ruby-aws-partitions
cp /tmp/ruby-aws-partitions/usr/share/rubygems-integration/all/gems/aws-partitions-*/*.json /usr/share/rubygems-integration/all/gems/aws-partitions-*/
```

**Comment by ShaunMaher** [comment]
As mentioned, this is not a bug.  Closing issue.

**Comment by morph027** [comment]
Thanks for the hint! Haven't noticed yet as i'm running deb-s3 from a user installation `gem install --user deb-s3`
