### ISSUE TITLE
Publish new packages to Rubygems?

### ISSUE THREAD

**Issue by rathboma** [deb-s3/deb-s3#9]
Hey new maintainers!

So glad I found this fork with all the nice upgrades.

Not sure if you've contacted @krobertson about gem ownership on rubygems, but it'd be great to migrate the rubygems version to this repository.

If not, could you publish as a new package name maybe?

I filed a likewise issue on the original repo - https://github.com/krobertson/deb-s3/issues/170

**Comment by hi-artem** [comment]
+1

**Comment by morph027** [comment]
Would be nice to do so, but unfortunately i do not have the ownership and @krobertson has not answered to me yet.

**Comment by krobertson** [comment]
@morph027 happened to see the email come in, you should have a request to confirm being added to the gem.

**Comment by morph027** [comment]
Wow, thank you! :star_struck:

**Comment by morph027** [comment]
Uploaded latest version to rubygems.
